services:
  # Plex Server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    hostname: plex
    volumes:
      - ${BASE_DIR}/plex/config:/config
      - ${MEDIA_DIR}/tv:/data/tv
      - ${MEDIA_DIR}/movies:/data/movies
      - ${MEDIA_DIR}/music:/data/music
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    networks:
      - internal
      - proxied
    restart: always
