services:
  # Lidarr
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ${BASE_DIR}/lidarr/config:/config
      - ${MEDIA_DIR}/music:/music
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
