services:
  # Transmission
  transmission:
    image: linuxserver/transmission:${TRANSMISSION_VERSION}
    container_name: transmission-${TRANSMISSION_VERSION}
    volumes:
      - ${BASE_DIR}/transmission:/data
      - ${DOWNLOAD_DIR}/complete:/data/completed
      - ${DOWNLOAD_DIR}/incomplete:/data/incomplete
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - TRANSMISSION_RPC_HOST_WHITELIST=*.${DOMAIN}
    networks:
      - proxied
      - internal
    expose:
      - 9091
    restart: always
