services:
  # Headphones
  headphones:
    image: linuxserver/headphones:latest
    container_name: headphones
    volumes:
      - ${BASE_DIR}/headphones/config:/config
      - ${MEDIA_DIR}/music:/music
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - internal
      - proxied
    restart: always
