services:
  # Mylar
  mylar:
    image: linuxserver/mylar:latest
    container_name: mylar
    volumes:
      - ${BASE_DIR}/mylar/config:/config
      - ${MEDIA_DIR}/comics:/comics
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
