services:
  # LazyLibrarian
  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    volumes:
      - ${BASE_DIR}/lazylibrarian/config:/config
      - ${MEDIA_DIR}/books:/books
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    networks:
      - proxied
      - internal
    restart: always
